name: harry_potter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2

  # network
  http: ^1.1.0

  # lottie animations
  lottie: ^2.4.0

  # border
  gradient_borders: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # clean code
  flutter_lints: ^2.0.2

  # test
  test: ^1.24.1

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/lora/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/lora/Lora-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lora/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/lora/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/lora/Lora-BoldItalic.ttf
          weight: 700
          style: italic
